version: '3.9'

services:
  postgres_db:
    image: postgres:15.3-bullseye
    container_name: postgres_db
    restart: always
    env_file:
      - docker.env
    ports:
      - "5432:5432"
      
  nestjs-api:
    image: nestjs-api
    container_name: nestjs-api
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres_db
